### PR TITLE
Add ability to use cards

### PR DESCRIPTION
**Pull request by robert-bo-davis**
This adds rudimentary support for hipchat cards.  Cards are much more extensible than the basic message format.

This maintains legacy behavior by default.

Here is the normal message, a collapsed card, an expanded card, and a collapsed failure:
screen shot 2016-05-01 at 10 52 42 am

### CODE REVIEW

**Comment by tboerger** [comment]
The code looks good so far, but now I know what you mean. Downstream is not really the correct icon reference

**Comment by jackspirou** [comment]
I need more time to really review this (I no longer use HipChat) but @mujiburger what do you think of having cards as the default behavior?

**Comment by robert-bo-davis** [comment]
I was worried about breaking somebody's custom templates for the original message style without telling them, but it doesn't look like that feature has been out for that long.  Providing a `disable_cards` flag so there is an easy fix if somebody needs their original template and doesn't want to spend time figuring out the card templating may be enough.  Let me know if that is the preferred behavior and I'll make it so.   

Any input on the default card template would be appreciated.   I went for less clutter in the collapsed card, but some may prefer more information without a click.  The "activity" which is what shows before the card is expanded supports a pretty full subset of HTML so it is flexible.

**Comment by bradrydzewski** [comment]
If cards have different behavior, and different configuration, should they be two separate plugins? Perhaps a hipchat and hipchat_card plugin? I would rather have two plugins with simple configurations than a mono-plugin with many configuration options that is more difficult to understand.

**Comment by bradrydzewski** [comment]
btw, the card functionality looks awesome

**Comment by robert-bo-davis** [comment]
Since it is buried in the documentation updates of the PR, I wanted to make sure it was clear.  As of right now, cards aren't supported on the hipchat mobile apps.  The plugin sends both formats and those apps display the default message.  A separate cards plugin would need to provide the same functionality as the main plugin in addition to handling cards.

**Comment by tboerger** [comment]
What should we do now? Migrate the drone config to 0.5 and merge this pr?

**Comment by bradrydzewski** [comment]
@tboerger I would prefer to accelerate efforts to create `plugins.drone.io` to allow developers to publish plugins or plugin variations

**Comment by tboerger** [comment]
@bradrydzewski so you want to close this PR?

**Comment by nlf** [comment]
code here lgtm

does need updated with master though, and also pending @bradrydzewski's decision here

**Comment by appleboy** [comment]
Any updates?

**Comment by jmccann** [comment]
@mujiburger I'm interested in supporting this.  If you mind updating with the 0.5 updates I made I would totally review.  Thanks!

**Comment by robert-bo-davis** [comment]
I took a quick look this morning. The conflict is strong with this one and I'm swamped at the moment. I'll take a harder look at it after the holidays.

**Comment by jmccann** [comment]
Yea, it was a major update to move to supporting Drone 0.5.  Take your time!

**Comment by jmccann** [comment]
Just curious if/how refactoring this plugin to use some hipchat golang libraries would affect this effort?  May make it easier?

Looking at potentially using either:
* https://github.com/tbruyelle/hipchat-go (seems like it may have some support for cards: https://github.com/tbruyelle/hipchat-go/blob/fc3453606408cfa87015e65ecb3309f9d1678317/hipchat/room.go#L74-L101)
* https://github.com/andybons/hipchat (may avoid this as I didn't see card stuff in it)

**Comment by jmccann** [comment]
Closing for now as I don't have time to update it and it seems to have gone stale.

**Pull request closed without merging**
